file_paths = {
    "person-left": "./figs/left_person.jpg",
    "person-mid": "./figs/mid_person.jpg",
    "person-right": "./figs/right_person.jpg",
    "animal_sheep": "./figs/animal_sheep.jpg",
    "animal_duck": "./figs/animal_duck.jpg",
    "animal_pig": "./figs/animal_pig.jpg",
    "bear_mid": "./figs/bear_mid.jpg",
    "bear_left": "./figs/bear_left.jpg",
    "bear_right": "./figs/bear_right.jpg",
    "hasky_ours": "./figs/hasky_ours.jpg",
    "bell_ours": "./figs/bell_ours.jpg",
    "dino_ours": "./figs/dino_ours.jpg",
    "people_ours": "./figs/people_ours.jpg",
    "plane_ours": "./figs/plane_ours.jpg",
    "building_ours": "./figs/building_ours.jpg",
    "baseball_ours": "./figs/baseball_ours.jpg",
    "duck_ours": "./figs/duck_ours.jpg",
    "kid_ours": "./figs/kid_ours.jpg",
}
